### ISSUE TITLE
const char * for file

### ISSUE THREAD

**Issue by niXman** [ProgerXP/SaneC#1]
Hi,

Why [this](https://github.com/ProgerXP/SaneC/blob/master/saneex.h#L209) member not just a `const char *` ?

**Comment by ProgerXP** [comment]
Why should it be? This struct can be used outside of the library. Exception info is always a copy ([e.g.](https://github.com/ProgerXP/SaneC/blob/master/saneex.c#L72)) so the caller is free to do whatever it wants with any struct member.

**Comment by niXman** [comment]
if I understood the code correctly, the `file` member used to provide the file name (`__FILE__`) or hardcoded `"..."` string?
if yes - then is there any reason to copy file name into this member? why not just declare it as `const char *` and use the assignment like `.file = __FILE__;` or `.file = "..."`?

or I'm wrong?

**Comment by ProgerXP** [comment]
Generally - yes, `file` would be a constant string like one coming from `__FILE__` (set by `newex()` or other macros). However, this is not required and *saneex* is making no assumptions about it. `file` could be used for anything just like `message`, e.g. for function names (if the client code is somehow tracking them) or other strings that can reside in heap or on stack.

I believe this extra copying has negligible impact on the performance because file names are very short. Avoiding pointers is also a plus.
